#!/bin/sh

. /etc/rc.subr

installdir="/home/defluxio/defluxio/software/server"
configfile="/home/defluxio/defluxio/software/server/defluxio.conf"

name=defluxiod
rcvar=defluxiod_enable

load_rc_config $name
pidfile=/var/run/defluxiod.pid
start_cmd=defluxiod_start
stop_postcmd=defluxiod_cleanup

command="${installdir}/server"
command_args="-config=${configfile}"

defluxiod_start() {
	echo "Starting defluxiod."
	touch ${pidfile}
	/usr/sbin/daemon -cf -p ${pidfile} ${command} ${command_args}
}

defluxiod_cleanup() {
	[ -f ${pidfile} ] && rm ${pidfile}
}

run_rc_command "$1"
